CREATE INDEX idx_artifact_scope ON knowledge_artifacts (product, domain, current_status, source_system);
CREATE INDEX idx_revision_stale ON knowledge_revisions (stale_after);
CREATE INDEX idx_acl_knowledge_principal ON knowledge_acl (knowledge_id, principal_id);
CREATE INDEX idx_acl_knowledge_role ON knowledge_acl (knowledge_id, role_name);
CREATE INDEX idx_acl_knowledge_group ON knowledge_acl (knowledge_id, group_name);
CREATE INDEX idx_acl_knowledge_product ON knowledge_acl (knowledge_id, product);
CREATE INDEX idx_acl_knowledge_domain ON knowledge_acl (knowledge_id, domain);
CREATE INDEX idx_acl_knowledge_classification ON knowledge_acl (knowledge_id, classification);
CREATE INDEX idx_audit_principal_time ON knowledge_audit_events (principal_id, created_at);
CREATE INDEX idx_audit_operation_time ON knowledge_audit_events (operation, created_at);
